#!/usr/bin/env bash
# setup domains

# variables & parameters
subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
sub="$2"

func () {
  # func variables
  sub="$2"
  INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
  IP=$(echo "$INFO" | awk '{print $5}')
  RECORD=$(echo "$INFO" | awk '{print $4}')

  echo "The subdomain $sub$is a $RECORD record and points to $IP${reset}"
}

if [ "$1" ]; then
  for subs in "${subdomains[@]}"; do
    func "$domain" "$subs"
  done
elif [ "$2" ]; then
  func "$domain" "$sub"
fi
