#!/usr/bin/env bash
# redirection

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# syntax: sed -i "s/string_to_replace/$new_string/" file
sudo sed -i '30i ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/nginx.conf
sudo service nginx restart
