#!/usr/bin/env bash
# redirection

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# syntax: sed -i "s/string_to_replace/$new_string/" file
sudo sed -i '/listen 80 default_server/a location = /redirect_me  https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/nginx.conf
sudo service nginx restart
