#!/usr/bin/env bash
# 404 page

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" >> /var/www/html/404.html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   # index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo nginx -s restart
