#!/usr/bin/env bash
# create environment setup

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '/root \/var\/www\/html/a \   error_page 404 /error_404.html;\n\   location = /error_404.html { \n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a \    rewrite ^/redirect_me(/.*)?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a \    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
