#!/usr/bin/env bash
# create environment setup
sudo apt-get update -y
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart

