#!/usr/bin/env bash
# setup load balancer

sudo apt-get update -y
sudo apt install haproxy -y

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo "backend web_servers" >> /etc/haproxy/haproxy.cfg
sudo sed -i '/backend web_servers/a \
mode http \
balance roundrobin \
server s1 18.234.192.140:80 check \
server s2 100.27.12.25:80 check \
' /etc/haproxy

sudo service haproxy reload
