#!/usr/bin/env bash
# setup load balancer

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '/root \/var\/www\/html/a \
  error_page 404 /error_404.html; \
  location = /error_404.html { \
    internal; \
  }' /etc/nginx/sites-enabled/default

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me(/.*)?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart

sudo apt install haproxy -y

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo "backend web_servers" >> /etc/haproxy/haproxy.cfg
sudo sed -i '/backend web_servers/a \
mode http \
balance roundrobin \
server s1 18.234.192.140:80 check \
server s2 100.27.12.25:80 check \
' /etc/haproxy

sudo service haproxy reload
