#!/usr/bin/env bash
# do lots of stuff

sudo touch /var/run/myscript.pid
sudo chmod u+x /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
trap "echo I hate the kill command; sudo rm /var/run/myscript.pid" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm /var/run/myscript.pid" SIGQUIT

while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
