#!/usr/bin/env bash
# connect without passwordssh-copy-id ubuntu@100.27.12.25
echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
sudo service ssh restart
ssh -A -i ~/.ssh/school ubuntu@100.27.12.25
